spring.datasource.url=jdbc:postgresql://127.0.0.1:54322/postgres?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=postgres

adra.brevo.api-key=${BREVO_API_KEY}
adra.brevo.remetente-email=naoresponda@adra.org.br
adra.brevo.remetente-nome=ADRA Araraquara
adra.frontend.url=http://localhost:4200