spring.config.import=optional:file:.env.stage[.properties]

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?currentSchema=adra&stringtype=unspecified
spring.datasource.username=postgres.moorxvcnxesniwaaaksm
spring.datasource.password=${SUPABASE_PASSWORD}

adra.supabase.url=https://moorxvcnxesniwaaaksm.supabase.co
adra.supabase.jwks-uri=https://moorxvcnxesniwaaaksm.supabase.co/auth/v1/.well-known/jwks.json
adra.supabase.service-key=${SUPABASE_SERVICE_KEY}
adra.jwt.segredo=${ADRA_JWT_SEGREDO}

adra.brevo.api-key=${BREVO_API_KEY}
adra.brevo.remetente-email=naoresponda@adra.org.br
adra.brevo.remetente-nome=ADRA Araraquara
adra.frontend.url=http://localhost:4200