spring.datasource.url=jdbc:postgresql://db.kceyjdtxmxkgfhihatip.supabase.co:5432/postgres?currentSchema=adra&stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}

adra.supabase.jwks-uri=https://kceyjdtxmxkgfhihatip.supabase.co/auth/v1/.well-known/jwks.json
adra.supabase.url=https://kceyjdtxmxkgfhihatip.supabase.co
