spring.datasource.url=jdbc:postgresql://db.moorxvcnxesniwaaaksm.supabase.co:5432/postgres?currentSchema=adra&stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}
adra.supabase.jwks-uri=https://moorxvcnxesniwaaaksm.supabase.co/auth/v1/.well-known/jwks.json
adra.supabase.url=https://moorxvcnxesniwaaaksm.supabase.co
