spring.config.import=optional:file:.env.prod[.properties]

spring.datasource.url=jdbc:postgresql://db.kceyjdtxmxkgfhihatip.supabase.co:5432/postgres?currentSchema=adra&stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}

adra.supabase.url=https://kceyjdtxmxkgfhihatip.supabase.co
adra.supabase.jwks-uri=https://kceyjdtxmxkgfhihatip.supabase.co/auth/v1/.well-known/jwks.json
adra.supabase.service-key=${SUPABASE_SERVICE_KEY}
adra.jwt.segredo=${ADRA_JWT_SEGREDO}
